### ISSUE TITLE
vocab = load_vocab('../full_idxr-obj')

### ISSUE THREAD

**Issue by qigeshige** [jjalfaro9/CXR-ReportGen#3]
hello,could you please tell me where the way is?
what is this document ?
It is in the embeddings.ipynb.
vocab = load_vocab('../full_idxr-obj')

**Comment by jjalfaro9** [comment]
Yo 👋
The document contains an index for each unique word in the reports.

`full_idxr-obj` can be generated by running https://github.com/jjalfaro9/CXR-ReportGen/blob/428ae23f9ed2004e81c923f66b3e33041f305f11/project/generate_indexer.py#L78-L104

**Comment by qigeshige** [comment]
> Yo 👋
> The document contains an index for each unique word in the reports.
> 
> `full_idxr-obj` can be generated by running
> 
> https://github.com/jjalfaro9/CXR-ReportGen/blob/428ae23f9ed2004e81c923f66b3e33041f305f11/project/generate_indexer.py#L78-L104

Thank you. I also want to know, because there are too many files, what is the running order.Thank you very much.

**Comment by jjalfaro9** [comment]
Hi! Sorry, been busy!

Once you have the data, the indexer object, the  `glove256_vocab_full.kv`  you can just run main to train the model. 
https://github.com/jjalfaro9/CXR-ReportGen/blob/428ae23f9ed2004e81c923f66b3e33041f305f11/project/main.py#L14-L82
